# Workflow syntax:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: cpp-linter

on:
  pull_request:
    branches:
      - main

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create compile_commands.json
        run: |
          cmake --version
          cmake . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=on
          
      - uses: ZedThree/clang-tidy-review@v0.8.0
