# Workflow syntax:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: cpp-linter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ZedThree/clang-tidy-review@v0.8.0
        id: review
        with:
          # CMake command to run in order to generate compile_commands.json
          cmake_command: cmake . -DCMAKE_EXPORT_COMPILE_COMMANDS=on
