name: Process test and benchmark results
on:
  workflow_run:
    workflows: ['Unit tests']
    types: 
      - completed

jobs: 
  post_test_results:
    name: Post test results
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'
    steps:
    - uses: haya14busa/action-workflow_run-status@v1
    
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Download all workflow run artifacts
      uses: dawidd6/action-download-artifact@v2
      with:
        path: artifacts
        workflow: Tests.yml
        run_id: ${{ github.event.workflow_run.id }}
        
    - name: Read the pr_num file
      id: pr_num_reader
      uses: juliangruber/read-file-action@v1.0.0
      with:
        path: ./artifacts/pr_num/pr_num.txt

    - name: Test Report
      uses: dorny/test-reporter@v1
      with:
        name: Test report
        path: ./build/test_results/*.xml
        reporter: java-junit
    
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}
        path: gh-pages

    - name: Install deps
      run: pip3 install pandas

    - name: Process benchmarks
      run: python3 ${{github.workspace}}/ci/process_benchmark_data.py ${GITHUB_SHA::8} "${{github.event.head_commit.message}}"

    - name: Compare results
      run: |
        python3 ${{github.workspace}}/ci/compare_results.py > comment-body.txt
        body=$(cat comment-body.txt)
        body="${body//'%'/'%25'}"
        body="${body//$'\n'/'%0A'}"
        body="${body//$'\r'/'%0D'}" 
        echo ::set-output name=body::$body
      id: results
      
    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      if: ${{ github.event.workflow_run.event == 'pull_request' }}
      with:
        issue-number: ${{ steps.pr_num_reader.outputs.content }}
        comment-author: 'github-actions[bot]'
        body-includes: GCC
        
    - name: Create comment
      if: ${{ github.event.workflow_run.event != 'pull_request' }}
      uses: peter-evans/commit-comment@v2
      with:
        body: ${{ steps.results.outputs.body }}
        
    - name: Update comment
      uses: peter-evans/create-or-update-comment@v2
      if: ${{ github.event.workflow_run.event == 'pull_request' }}
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ steps.pr_num_reader.outputs.content }}
        body: ${{ steps.results.outputs.body }}
        edit-mode: replace

    - name: Install deps
      run: pip3 install plotly
      if: ${{ github.event.workflow_run.event != 'pull_request' }}

    - name: Create html
      run: python3 ${{github.workspace}}/ci/create_graphs_for_benchmark_data.py 
      if: ${{ github.event.workflow_run.event != 'pull_request' }}

    - name: Upload html
      uses: actions/upload-artifact@v3
      if: ${{ github.event.workflow_run.event != 'pull_request' }}
      with:
        name: benchmark.html
        path: ./gh-pages/benchmark.html

    - name: Deploy to github pages
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event.workflow_run.event != 'pull_request' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages

