name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    
    strategy:
      matrix:
        config:
        -  name: "Linux GCC"
           os: ubuntu-latest
           cc: "gcc-10"
           cxx: "g++-10"
           relative_path_bench: "build/bin/rpp_tests"
        -  name: "Linux CLANG"
           os: ubuntu-latest
           cc: "clang" 
           cxx: "clang++"
           relative_path_bench: "build/bin/rpp_tests"
        -  name: "Windows MSVC"
           os: windows-latest
           cc: "cl"
           cxx: "cl"
           relative_path_bench: "build/bin/Release/rpp_tests"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.TOKEN }}

    - name: Setup cache
      uses: mikehardy/buildcache-action@v1
      
      with:
        cache_key: ${{ matrix.config.name }}
        
    - name: Update env
      if: matrix.config.os == 'windows-latest'
      run: |
        echo "BUILDCACHE_IMPERSONATE=cl.exe" >> $GITHUB_ENV
        echo "CLToolExe=buildcache.exe" >> $GITHUB_ENV
      
    - name: Configure CMake
      env:
        CC: ${{ matrix.config.cc }}
        CXX: ${{ matrix.config.cxx }}
      run: cmake -B ${{github.workspace}}/build -DAUTOTESTS=1 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER_LAUNCHER=buildcache -DCMAKE_CXX_COMPILER_LAUNCHER=buildcache
        
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel 4

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
      
    - name: Test Report ${{ matrix.config.name }}
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Test report ${{ matrix.config.name }} 
        path: ./build/test_results/*.xml
        reporter: java-junit

    - name: Run benchmarks only
      run: ${{github.workspace}}/${{ matrix.config.relative_path_bench }} [benchmark] -r xml -o ${{github.workspace}}/build/test_results/benchmark_result.txt
      if: matrix.config.relative_path_bench != ''

    - name: Upload parsed results
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.config.name }}
        path: ${{github.workspace}}/build/test_results/benchmark_result.txt

  process:
    name: Process benchmark results
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.TOKEN }}

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts
    
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
        token: ${{ secrets.TOKEN }}
        path: gh-pages
    - name: Log
      run: ls -R

    - name: Install deps
      run: pip3 install pandas

    - name: Process benchmarks
      run: python3 ${{github.workspace}}/ci/process_benchmark_data.py ${GITHUB_SHA::8} "${{github.event.head_commit.message}}"

    - name: Compare results
      run: |
        python3 ${{github.workspace}}/ci/compare_results.py > comment-body.txt
        body=$(cat comment-body.txt)
        body="${body//'%'/'%25'}"
        body="${body//$'\n'/'%0A'}"
        body="${body//$'\r'/'%0D'}" 
        echo ::set-output name=body::$body
      id: results
      
    - name: Create commit comment
      uses: peter-evans/commit-comment@v1
      with:
        body: ${{ steps.results.outputs.body }}

    - name: Install deps
      run: pip3 install plotly
      if: github.event_name != 'pull_request'

    - name: Create html
      run: python3 ${{github.workspace}}/ci/create_graphs_for_benchmark_data.py 
      if: github.event_name != 'pull_request'


    - name: Upload html
      uses: actions/upload-artifact@v3
      if: github.event_name != 'pull_request'
      with:
        name: benchmark.html
        path: ./gh-pages/benchmark.html

    - name: Deploy to github pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.event_name != 'pull_request'
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./gh-pages
